export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCCES = 'ORDER_CREATE_SUCCES';
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL';
export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET';

export const ORDER_DETAIL_REQUEST = 'ORDER_DETAIL_REQUEST';
export const ORDER_DETAIL_FAIL = 'ORDER_DETAIL_FAIL';
export const ORDER_DETAIL_SUCCESS = 'ORDER_DETAIL_SUCCESS';