const data = {
  products: [
    {
      _id: '1',
      name: 'Nike Slim Shirt',
      category: 'Shirts',
      image: '/image/product1.png',
      price: 120,
      countInStock: 10,
      brand: 'Polo',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '2',
      name: 'Uniqlo Nice model',
      category: 'Sweeter',
      image: '/image/product2.png',
      price: 100,
      countInStock: 30,
      brand: 'Uniqlo',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '3',
      name: 'Ripcurl cloud',
      category: 'School Bag',
      image: '/image/product3.png',
      price: 200,
      countInStock: 5,
      brand: 'Ripcurl',
      rating: 4.2,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '4',
      name: 'Cute Baby Clothing',
      category: 'Baby Cloth',
      image: '/image/product4.png',
      price: 100,
      countInStock: 11,
      brand: 'Matahari',
      rating: 3.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '5',
      name: 'Volkswagen T-shirt',
      category: 'T-shirts',
      image: '/image/product5.png',
      price: 130,
      countInStock: 50,
      brand: 'Black Label',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '6',
      name: 'Uniq Pouch Bag',
      category: 'Pouch Bag',
      image: '/image/product6.png',
      price: 50,
      countInStock: 100,
      brand: 'Kipling',
      rating: 4.6,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '7',
      name: 'Uniqlo Women T-shirt',
      category: 'T-shirt',
      image: '/image/product7.png',
      price: 180,
      countInStock: 20,
      brand: 'Uniqlo',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '8',
      name: 'Billabong Surfing Short Pants',
      category: 'Pants',
      image: '/image/product8.png',
      price: 300,
      countInStock: 30,
      brand: 'Billabong',
      rating: 4.9,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '9',
      name: 'Transparant Jacket',
      category: 'Jacket',
      image: '/image/product9.png',
      price: 400,
      countInStock: 0,
      brand: 'Erigo',
      rating: 2.0,
      numReviews: 10,
      description: 'high quality product',
    },
  ],
};
export default data;